/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UslugiRouteImport } from './routes/uslugi/route'
import { Route as IndexImport } from './routes/index'
import { Route as UslugiIndexImport } from './routes/uslugi/index'
import { Route as MapaUslugIndexImport } from './routes/mapa-uslug/index'
import { Route as UslugiCategoryIdImport } from './routes/uslugi/$categoryId'
import { Route as PanelUzytkownikaLayoutImport } from './routes/panel-uzytkownika/_layout'
import { Route as KategoriaCategoryIdImport } from './routes/kategoria/$categoryId'
import { Route as TypeProduktIdImport } from './routes/$type/$produktId'
import { Route as PanelUzytkownikaLayoutTwojeUslugiImport } from './routes/panel-uzytkownika/_layout/twoje-uslugi'
import { Route as PanelUzytkownikaLayoutTwojeProduktyImport } from './routes/panel-uzytkownika/_layout/twoje-produkty'
import { Route as PanelUzytkownikaLayoutTwojeDaneImport } from './routes/panel-uzytkownika/_layout/twoje-dane'
import { Route as PanelUzytkownikaLayoutTwojaUmowaImport } from './routes/panel-uzytkownika/_layout/twoja-umowa'
import { Route as PanelUzytkownikaLayoutTwojaStronaSprzedawcyImport } from './routes/panel-uzytkownika/_layout/twoja-strona-sprzedawcy'

// Create Virtual Routes

const PanelUzytkownikaImport = createFileRoute('/panel-uzytkownika')()

// Create/Update Routes

const PanelUzytkownikaRoute = PanelUzytkownikaImport.update({
  id: '/panel-uzytkownika',
  path: '/panel-uzytkownika',
  getParentRoute: () => rootRoute,
} as any)

const UslugiRouteRoute = UslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UslugiIndexRoute = UslugiIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UslugiRouteRoute,
} as any)

const MapaUslugIndexRoute = MapaUslugIndexImport.update({
  id: '/mapa-uslug/',
  path: '/mapa-uslug/',
  getParentRoute: () => rootRoute,
} as any)

const UslugiCategoryIdRoute = UslugiCategoryIdImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => UslugiRouteRoute,
} as any)

const PanelUzytkownikaLayoutRoute = PanelUzytkownikaLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => PanelUzytkownikaRoute,
} as any)

const KategoriaCategoryIdRoute = KategoriaCategoryIdImport.update({
  id: '/kategoria/$categoryId',
  path: '/kategoria/$categoryId',
  getParentRoute: () => rootRoute,
} as any)

const TypeProduktIdRoute = TypeProduktIdImport.update({
  id: '/$type/$produktId',
  path: '/$type/$produktId',
  getParentRoute: () => rootRoute,
} as any)

const PanelUzytkownikaLayoutTwojeUslugiRoute =
  PanelUzytkownikaLayoutTwojeUslugiImport.update({
    id: '/twoje-uslugi',
    path: '/twoje-uslugi',
    getParentRoute: () => PanelUzytkownikaLayoutRoute,
  } as any)

const PanelUzytkownikaLayoutTwojeProduktyRoute =
  PanelUzytkownikaLayoutTwojeProduktyImport.update({
    id: '/twoje-produkty',
    path: '/twoje-produkty',
    getParentRoute: () => PanelUzytkownikaLayoutRoute,
  } as any)

const PanelUzytkownikaLayoutTwojeDaneRoute =
  PanelUzytkownikaLayoutTwojeDaneImport.update({
    id: '/twoje-dane',
    path: '/twoje-dane',
    getParentRoute: () => PanelUzytkownikaLayoutRoute,
  } as any)

const PanelUzytkownikaLayoutTwojaUmowaRoute =
  PanelUzytkownikaLayoutTwojaUmowaImport.update({
    id: '/twoja-umowa',
    path: '/twoja-umowa',
    getParentRoute: () => PanelUzytkownikaLayoutRoute,
  } as any)

const PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute =
  PanelUzytkownikaLayoutTwojaStronaSprzedawcyImport.update({
    id: '/twoja-strona-sprzedawcy',
    path: '/twoja-strona-sprzedawcy',
    getParentRoute: () => PanelUzytkownikaLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/uslugi': {
      id: '/uslugi'
      path: '/uslugi'
      fullPath: '/uslugi'
      preLoaderRoute: typeof UslugiRouteImport
      parentRoute: typeof rootRoute
    }
    '/$type/$produktId': {
      id: '/$type/$produktId'
      path: '/$type/$produktId'
      fullPath: '/$type/$produktId'
      preLoaderRoute: typeof TypeProduktIdImport
      parentRoute: typeof rootRoute
    }
    '/kategoria/$categoryId': {
      id: '/kategoria/$categoryId'
      path: '/kategoria/$categoryId'
      fullPath: '/kategoria/$categoryId'
      preLoaderRoute: typeof KategoriaCategoryIdImport
      parentRoute: typeof rootRoute
    }
    '/panel-uzytkownika': {
      id: '/panel-uzytkownika'
      path: '/panel-uzytkownika'
      fullPath: '/panel-uzytkownika'
      preLoaderRoute: typeof PanelUzytkownikaImport
      parentRoute: typeof rootRoute
    }
    '/panel-uzytkownika/_layout': {
      id: '/panel-uzytkownika/_layout'
      path: '/panel-uzytkownika'
      fullPath: '/panel-uzytkownika'
      preLoaderRoute: typeof PanelUzytkownikaLayoutImport
      parentRoute: typeof PanelUzytkownikaRoute
    }
    '/uslugi/$categoryId': {
      id: '/uslugi/$categoryId'
      path: '/$categoryId'
      fullPath: '/uslugi/$categoryId'
      preLoaderRoute: typeof UslugiCategoryIdImport
      parentRoute: typeof UslugiRouteImport
    }
    '/mapa-uslug/': {
      id: '/mapa-uslug/'
      path: '/mapa-uslug'
      fullPath: '/mapa-uslug'
      preLoaderRoute: typeof MapaUslugIndexImport
      parentRoute: typeof rootRoute
    }
    '/uslugi/': {
      id: '/uslugi/'
      path: '/'
      fullPath: '/uslugi/'
      preLoaderRoute: typeof UslugiIndexImport
      parentRoute: typeof UslugiRouteImport
    }
    '/panel-uzytkownika/_layout/twoja-strona-sprzedawcy': {
      id: '/panel-uzytkownika/_layout/twoja-strona-sprzedawcy'
      path: '/twoja-strona-sprzedawcy'
      fullPath: '/panel-uzytkownika/twoja-strona-sprzedawcy'
      preLoaderRoute: typeof PanelUzytkownikaLayoutTwojaStronaSprzedawcyImport
      parentRoute: typeof PanelUzytkownikaLayoutImport
    }
    '/panel-uzytkownika/_layout/twoja-umowa': {
      id: '/panel-uzytkownika/_layout/twoja-umowa'
      path: '/twoja-umowa'
      fullPath: '/panel-uzytkownika/twoja-umowa'
      preLoaderRoute: typeof PanelUzytkownikaLayoutTwojaUmowaImport
      parentRoute: typeof PanelUzytkownikaLayoutImport
    }
    '/panel-uzytkownika/_layout/twoje-dane': {
      id: '/panel-uzytkownika/_layout/twoje-dane'
      path: '/twoje-dane'
      fullPath: '/panel-uzytkownika/twoje-dane'
      preLoaderRoute: typeof PanelUzytkownikaLayoutTwojeDaneImport
      parentRoute: typeof PanelUzytkownikaLayoutImport
    }
    '/panel-uzytkownika/_layout/twoje-produkty': {
      id: '/panel-uzytkownika/_layout/twoje-produkty'
      path: '/twoje-produkty'
      fullPath: '/panel-uzytkownika/twoje-produkty'
      preLoaderRoute: typeof PanelUzytkownikaLayoutTwojeProduktyImport
      parentRoute: typeof PanelUzytkownikaLayoutImport
    }
    '/panel-uzytkownika/_layout/twoje-uslugi': {
      id: '/panel-uzytkownika/_layout/twoje-uslugi'
      path: '/twoje-uslugi'
      fullPath: '/panel-uzytkownika/twoje-uslugi'
      preLoaderRoute: typeof PanelUzytkownikaLayoutTwojeUslugiImport
      parentRoute: typeof PanelUzytkownikaLayoutImport
    }
  }
}

// Create and export the route tree

interface UslugiRouteRouteChildren {
  UslugiCategoryIdRoute: typeof UslugiCategoryIdRoute
  UslugiIndexRoute: typeof UslugiIndexRoute
}

const UslugiRouteRouteChildren: UslugiRouteRouteChildren = {
  UslugiCategoryIdRoute: UslugiCategoryIdRoute,
  UslugiIndexRoute: UslugiIndexRoute,
}

const UslugiRouteRouteWithChildren = UslugiRouteRoute._addFileChildren(
  UslugiRouteRouteChildren,
)

interface PanelUzytkownikaLayoutRouteChildren {
  PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute: typeof PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute
  PanelUzytkownikaLayoutTwojaUmowaRoute: typeof PanelUzytkownikaLayoutTwojaUmowaRoute
  PanelUzytkownikaLayoutTwojeDaneRoute: typeof PanelUzytkownikaLayoutTwojeDaneRoute
  PanelUzytkownikaLayoutTwojeProduktyRoute: typeof PanelUzytkownikaLayoutTwojeProduktyRoute
  PanelUzytkownikaLayoutTwojeUslugiRoute: typeof PanelUzytkownikaLayoutTwojeUslugiRoute
}

const PanelUzytkownikaLayoutRouteChildren: PanelUzytkownikaLayoutRouteChildren =
  {
    PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute:
      PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute,
    PanelUzytkownikaLayoutTwojaUmowaRoute:
      PanelUzytkownikaLayoutTwojaUmowaRoute,
    PanelUzytkownikaLayoutTwojeDaneRoute: PanelUzytkownikaLayoutTwojeDaneRoute,
    PanelUzytkownikaLayoutTwojeProduktyRoute:
      PanelUzytkownikaLayoutTwojeProduktyRoute,
    PanelUzytkownikaLayoutTwojeUslugiRoute:
      PanelUzytkownikaLayoutTwojeUslugiRoute,
  }

const PanelUzytkownikaLayoutRouteWithChildren =
  PanelUzytkownikaLayoutRoute._addFileChildren(
    PanelUzytkownikaLayoutRouteChildren,
  )

interface PanelUzytkownikaRouteChildren {
  PanelUzytkownikaLayoutRoute: typeof PanelUzytkownikaLayoutRouteWithChildren
}

const PanelUzytkownikaRouteChildren: PanelUzytkownikaRouteChildren = {
  PanelUzytkownikaLayoutRoute: PanelUzytkownikaLayoutRouteWithChildren,
}

const PanelUzytkownikaRouteWithChildren =
  PanelUzytkownikaRoute._addFileChildren(PanelUzytkownikaRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/uslugi': typeof UslugiRouteRouteWithChildren
  '/$type/$produktId': typeof TypeProduktIdRoute
  '/kategoria/$categoryId': typeof KategoriaCategoryIdRoute
  '/panel-uzytkownika': typeof PanelUzytkownikaLayoutRouteWithChildren
  '/uslugi/$categoryId': typeof UslugiCategoryIdRoute
  '/mapa-uslug': typeof MapaUslugIndexRoute
  '/uslugi/': typeof UslugiIndexRoute
  '/panel-uzytkownika/twoja-strona-sprzedawcy': typeof PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute
  '/panel-uzytkownika/twoja-umowa': typeof PanelUzytkownikaLayoutTwojaUmowaRoute
  '/panel-uzytkownika/twoje-dane': typeof PanelUzytkownikaLayoutTwojeDaneRoute
  '/panel-uzytkownika/twoje-produkty': typeof PanelUzytkownikaLayoutTwojeProduktyRoute
  '/panel-uzytkownika/twoje-uslugi': typeof PanelUzytkownikaLayoutTwojeUslugiRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$type/$produktId': typeof TypeProduktIdRoute
  '/kategoria/$categoryId': typeof KategoriaCategoryIdRoute
  '/panel-uzytkownika': typeof PanelUzytkownikaLayoutRouteWithChildren
  '/uslugi/$categoryId': typeof UslugiCategoryIdRoute
  '/mapa-uslug': typeof MapaUslugIndexRoute
  '/uslugi': typeof UslugiIndexRoute
  '/panel-uzytkownika/twoja-strona-sprzedawcy': typeof PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute
  '/panel-uzytkownika/twoja-umowa': typeof PanelUzytkownikaLayoutTwojaUmowaRoute
  '/panel-uzytkownika/twoje-dane': typeof PanelUzytkownikaLayoutTwojeDaneRoute
  '/panel-uzytkownika/twoje-produkty': typeof PanelUzytkownikaLayoutTwojeProduktyRoute
  '/panel-uzytkownika/twoje-uslugi': typeof PanelUzytkownikaLayoutTwojeUslugiRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/uslugi': typeof UslugiRouteRouteWithChildren
  '/$type/$produktId': typeof TypeProduktIdRoute
  '/kategoria/$categoryId': typeof KategoriaCategoryIdRoute
  '/panel-uzytkownika': typeof PanelUzytkownikaRouteWithChildren
  '/panel-uzytkownika/_layout': typeof PanelUzytkownikaLayoutRouteWithChildren
  '/uslugi/$categoryId': typeof UslugiCategoryIdRoute
  '/mapa-uslug/': typeof MapaUslugIndexRoute
  '/uslugi/': typeof UslugiIndexRoute
  '/panel-uzytkownika/_layout/twoja-strona-sprzedawcy': typeof PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute
  '/panel-uzytkownika/_layout/twoja-umowa': typeof PanelUzytkownikaLayoutTwojaUmowaRoute
  '/panel-uzytkownika/_layout/twoje-dane': typeof PanelUzytkownikaLayoutTwojeDaneRoute
  '/panel-uzytkownika/_layout/twoje-produkty': typeof PanelUzytkownikaLayoutTwojeProduktyRoute
  '/panel-uzytkownika/_layout/twoje-uslugi': typeof PanelUzytkownikaLayoutTwojeUslugiRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/uslugi'
    | '/$type/$produktId'
    | '/kategoria/$categoryId'
    | '/panel-uzytkownika'
    | '/uslugi/$categoryId'
    | '/mapa-uslug'
    | '/uslugi/'
    | '/panel-uzytkownika/twoja-strona-sprzedawcy'
    | '/panel-uzytkownika/twoja-umowa'
    | '/panel-uzytkownika/twoje-dane'
    | '/panel-uzytkownika/twoje-produkty'
    | '/panel-uzytkownika/twoje-uslugi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$type/$produktId'
    | '/kategoria/$categoryId'
    | '/panel-uzytkownika'
    | '/uslugi/$categoryId'
    | '/mapa-uslug'
    | '/uslugi'
    | '/panel-uzytkownika/twoja-strona-sprzedawcy'
    | '/panel-uzytkownika/twoja-umowa'
    | '/panel-uzytkownika/twoje-dane'
    | '/panel-uzytkownika/twoje-produkty'
    | '/panel-uzytkownika/twoje-uslugi'
  id:
    | '__root__'
    | '/'
    | '/uslugi'
    | '/$type/$produktId'
    | '/kategoria/$categoryId'
    | '/panel-uzytkownika'
    | '/panel-uzytkownika/_layout'
    | '/uslugi/$categoryId'
    | '/mapa-uslug/'
    | '/uslugi/'
    | '/panel-uzytkownika/_layout/twoja-strona-sprzedawcy'
    | '/panel-uzytkownika/_layout/twoja-umowa'
    | '/panel-uzytkownika/_layout/twoje-dane'
    | '/panel-uzytkownika/_layout/twoje-produkty'
    | '/panel-uzytkownika/_layout/twoje-uslugi'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UslugiRouteRoute: typeof UslugiRouteRouteWithChildren
  TypeProduktIdRoute: typeof TypeProduktIdRoute
  KategoriaCategoryIdRoute: typeof KategoriaCategoryIdRoute
  PanelUzytkownikaRoute: typeof PanelUzytkownikaRouteWithChildren
  MapaUslugIndexRoute: typeof MapaUslugIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UslugiRouteRoute: UslugiRouteRouteWithChildren,
  TypeProduktIdRoute: TypeProduktIdRoute,
  KategoriaCategoryIdRoute: KategoriaCategoryIdRoute,
  PanelUzytkownikaRoute: PanelUzytkownikaRouteWithChildren,
  MapaUslugIndexRoute: MapaUslugIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/uslugi",
        "/$type/$produktId",
        "/kategoria/$categoryId",
        "/panel-uzytkownika",
        "/mapa-uslug/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/uslugi": {
      "filePath": "uslugi/route.tsx",
      "children": [
        "/uslugi/$categoryId",
        "/uslugi/"
      ]
    },
    "/$type/$produktId": {
      "filePath": "$type/$produktId.tsx"
    },
    "/kategoria/$categoryId": {
      "filePath": "kategoria/$categoryId.tsx"
    },
    "/panel-uzytkownika": {
      "filePath": "panel-uzytkownika",
      "children": [
        "/panel-uzytkownika/_layout"
      ]
    },
    "/panel-uzytkownika/_layout": {
      "filePath": "panel-uzytkownika/_layout.tsx",
      "parent": "/panel-uzytkownika",
      "children": [
        "/panel-uzytkownika/_layout/twoja-strona-sprzedawcy",
        "/panel-uzytkownika/_layout/twoja-umowa",
        "/panel-uzytkownika/_layout/twoje-dane",
        "/panel-uzytkownika/_layout/twoje-produkty",
        "/panel-uzytkownika/_layout/twoje-uslugi"
      ]
    },
    "/uslugi/$categoryId": {
      "filePath": "uslugi/$categoryId.tsx",
      "parent": "/uslugi"
    },
    "/mapa-uslug/": {
      "filePath": "mapa-uslug/index.tsx"
    },
    "/uslugi/": {
      "filePath": "uslugi/index.tsx",
      "parent": "/uslugi"
    },
    "/panel-uzytkownika/_layout/twoja-strona-sprzedawcy": {
      "filePath": "panel-uzytkownika/_layout/twoja-strona-sprzedawcy.tsx",
      "parent": "/panel-uzytkownika/_layout"
    },
    "/panel-uzytkownika/_layout/twoja-umowa": {
      "filePath": "panel-uzytkownika/_layout/twoja-umowa.tsx",
      "parent": "/panel-uzytkownika/_layout"
    },
    "/panel-uzytkownika/_layout/twoje-dane": {
      "filePath": "panel-uzytkownika/_layout/twoje-dane.tsx",
      "parent": "/panel-uzytkownika/_layout"
    },
    "/panel-uzytkownika/_layout/twoje-produkty": {
      "filePath": "panel-uzytkownika/_layout/twoje-produkty.tsx",
      "parent": "/panel-uzytkownika/_layout"
    },
    "/panel-uzytkownika/_layout/twoje-uslugi": {
      "filePath": "panel-uzytkownika/_layout/twoje-uslugi.tsx",
      "parent": "/panel-uzytkownika/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
