/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProduktyIndexImport } from './routes/produkty/index'
import { Route as ProduktyProduktIdImport } from './routes/produkty/$produktId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProduktyIndexRoute = ProduktyIndexImport.update({
  id: '/produkty/',
  path: '/produkty/',
  getParentRoute: () => rootRoute,
} as any)

const ProduktyProduktIdRoute = ProduktyProduktIdImport.update({
  id: '/produkty/$produktId',
  path: '/produkty/$produktId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/produkty/$produktId': {
      id: '/produkty/$produktId'
      path: '/produkty/$produktId'
      fullPath: '/produkty/$produktId'
      preLoaderRoute: typeof ProduktyProduktIdImport
      parentRoute: typeof rootRoute
    }
    '/produkty/': {
      id: '/produkty/'
      path: '/produkty'
      fullPath: '/produkty'
      preLoaderRoute: typeof ProduktyIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/produkty/$produktId': typeof ProduktyProduktIdRoute
  '/produkty': typeof ProduktyIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/produkty/$produktId': typeof ProduktyProduktIdRoute
  '/produkty': typeof ProduktyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/produkty/$produktId': typeof ProduktyProduktIdRoute
  '/produkty/': typeof ProduktyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/produkty/$produktId' | '/produkty'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/produkty/$produktId' | '/produkty'
  id: '__root__' | '/' | '/produkty/$produktId' | '/produkty/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProduktyProduktIdRoute: typeof ProduktyProduktIdRoute
  ProduktyIndexRoute: typeof ProduktyIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProduktyProduktIdRoute: ProduktyProduktIdRoute,
  ProduktyIndexRoute: ProduktyIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/produkty/$produktId",
        "/produkty/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/produkty/$produktId": {
      "filePath": "produkty/$produktId.tsx"
    },
    "/produkty/": {
      "filePath": "produkty/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
