/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UslugiCategoryIdImport } from './routes/uslugi/$categoryId'
import { Route as ProduktProduktIdImport } from './routes/produkt/$produktId'
import { Route as PanelUzytkownikaLayoutImport } from './routes/panel-uzytkownika/_layout'
import { Route as KategoriaCategoryIdImport } from './routes/kategoria/$categoryId'
import { Route as PanelUzytkownikaLayoutTwojeProduktyImport } from './routes/panel-uzytkownika/_layout/twoje-produkty'
import { Route as PanelUzytkownikaLayoutTwojeDaneImport } from './routes/panel-uzytkownika/_layout/twoje-dane'
import { Route as PanelUzytkownikaLayoutTwojaUmowaImport } from './routes/panel-uzytkownika/_layout/twoja-umowa'
import { Route as PanelUzytkownikaLayoutTwojaStronaSprzedawcyImport } from './routes/panel-uzytkownika/_layout/twoja-strona-sprzedawcy'

// Create Virtual Routes

const PanelUzytkownikaImport = createFileRoute('/panel-uzytkownika')()

// Create/Update Routes

const PanelUzytkownikaRoute = PanelUzytkownikaImport.update({
  id: '/panel-uzytkownika',
  path: '/panel-uzytkownika',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UslugiCategoryIdRoute = UslugiCategoryIdImport.update({
  id: '/uslugi/$categoryId',
  path: '/uslugi/$categoryId',
  getParentRoute: () => rootRoute,
} as any)

const ProduktProduktIdRoute = ProduktProduktIdImport.update({
  id: '/produkt/$produktId',
  path: '/produkt/$produktId',
  getParentRoute: () => rootRoute,
} as any)

const PanelUzytkownikaLayoutRoute = PanelUzytkownikaLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => PanelUzytkownikaRoute,
} as any)

const KategoriaCategoryIdRoute = KategoriaCategoryIdImport.update({
  id: '/kategoria/$categoryId',
  path: '/kategoria/$categoryId',
  getParentRoute: () => rootRoute,
} as any)

const PanelUzytkownikaLayoutTwojeProduktyRoute =
  PanelUzytkownikaLayoutTwojeProduktyImport.update({
    id: '/twoje-produkty',
    path: '/twoje-produkty',
    getParentRoute: () => PanelUzytkownikaLayoutRoute,
  } as any)

const PanelUzytkownikaLayoutTwojeDaneRoute =
  PanelUzytkownikaLayoutTwojeDaneImport.update({
    id: '/twoje-dane',
    path: '/twoje-dane',
    getParentRoute: () => PanelUzytkownikaLayoutRoute,
  } as any)

const PanelUzytkownikaLayoutTwojaUmowaRoute =
  PanelUzytkownikaLayoutTwojaUmowaImport.update({
    id: '/twoja-umowa',
    path: '/twoja-umowa',
    getParentRoute: () => PanelUzytkownikaLayoutRoute,
  } as any)

const PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute =
  PanelUzytkownikaLayoutTwojaStronaSprzedawcyImport.update({
    id: '/twoja-strona-sprzedawcy',
    path: '/twoja-strona-sprzedawcy',
    getParentRoute: () => PanelUzytkownikaLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/kategoria/$categoryId': {
      id: '/kategoria/$categoryId'
      path: '/kategoria/$categoryId'
      fullPath: '/kategoria/$categoryId'
      preLoaderRoute: typeof KategoriaCategoryIdImport
      parentRoute: typeof rootRoute
    }
    '/panel-uzytkownika': {
      id: '/panel-uzytkownika'
      path: '/panel-uzytkownika'
      fullPath: '/panel-uzytkownika'
      preLoaderRoute: typeof PanelUzytkownikaImport
      parentRoute: typeof rootRoute
    }
    '/panel-uzytkownika/_layout': {
      id: '/panel-uzytkownika/_layout'
      path: '/panel-uzytkownika'
      fullPath: '/panel-uzytkownika'
      preLoaderRoute: typeof PanelUzytkownikaLayoutImport
      parentRoute: typeof PanelUzytkownikaRoute
    }
    '/produkt/$produktId': {
      id: '/produkt/$produktId'
      path: '/produkt/$produktId'
      fullPath: '/produkt/$produktId'
      preLoaderRoute: typeof ProduktProduktIdImport
      parentRoute: typeof rootRoute
    }
    '/uslugi/$categoryId': {
      id: '/uslugi/$categoryId'
      path: '/uslugi/$categoryId'
      fullPath: '/uslugi/$categoryId'
      preLoaderRoute: typeof UslugiCategoryIdImport
      parentRoute: typeof rootRoute
    }
    '/panel-uzytkownika/_layout/twoja-strona-sprzedawcy': {
      id: '/panel-uzytkownika/_layout/twoja-strona-sprzedawcy'
      path: '/twoja-strona-sprzedawcy'
      fullPath: '/panel-uzytkownika/twoja-strona-sprzedawcy'
      preLoaderRoute: typeof PanelUzytkownikaLayoutTwojaStronaSprzedawcyImport
      parentRoute: typeof PanelUzytkownikaLayoutImport
    }
    '/panel-uzytkownika/_layout/twoja-umowa': {
      id: '/panel-uzytkownika/_layout/twoja-umowa'
      path: '/twoja-umowa'
      fullPath: '/panel-uzytkownika/twoja-umowa'
      preLoaderRoute: typeof PanelUzytkownikaLayoutTwojaUmowaImport
      parentRoute: typeof PanelUzytkownikaLayoutImport
    }
    '/panel-uzytkownika/_layout/twoje-dane': {
      id: '/panel-uzytkownika/_layout/twoje-dane'
      path: '/twoje-dane'
      fullPath: '/panel-uzytkownika/twoje-dane'
      preLoaderRoute: typeof PanelUzytkownikaLayoutTwojeDaneImport
      parentRoute: typeof PanelUzytkownikaLayoutImport
    }
    '/panel-uzytkownika/_layout/twoje-produkty': {
      id: '/panel-uzytkownika/_layout/twoje-produkty'
      path: '/twoje-produkty'
      fullPath: '/panel-uzytkownika/twoje-produkty'
      preLoaderRoute: typeof PanelUzytkownikaLayoutTwojeProduktyImport
      parentRoute: typeof PanelUzytkownikaLayoutImport
    }
  }
}

// Create and export the route tree

interface PanelUzytkownikaLayoutRouteChildren {
  PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute: typeof PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute
  PanelUzytkownikaLayoutTwojaUmowaRoute: typeof PanelUzytkownikaLayoutTwojaUmowaRoute
  PanelUzytkownikaLayoutTwojeDaneRoute: typeof PanelUzytkownikaLayoutTwojeDaneRoute
  PanelUzytkownikaLayoutTwojeProduktyRoute: typeof PanelUzytkownikaLayoutTwojeProduktyRoute
}

const PanelUzytkownikaLayoutRouteChildren: PanelUzytkownikaLayoutRouteChildren =
  {
    PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute:
      PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute,
    PanelUzytkownikaLayoutTwojaUmowaRoute:
      PanelUzytkownikaLayoutTwojaUmowaRoute,
    PanelUzytkownikaLayoutTwojeDaneRoute: PanelUzytkownikaLayoutTwojeDaneRoute,
    PanelUzytkownikaLayoutTwojeProduktyRoute:
      PanelUzytkownikaLayoutTwojeProduktyRoute,
  }

const PanelUzytkownikaLayoutRouteWithChildren =
  PanelUzytkownikaLayoutRoute._addFileChildren(
    PanelUzytkownikaLayoutRouteChildren,
  )

interface PanelUzytkownikaRouteChildren {
  PanelUzytkownikaLayoutRoute: typeof PanelUzytkownikaLayoutRouteWithChildren
}

const PanelUzytkownikaRouteChildren: PanelUzytkownikaRouteChildren = {
  PanelUzytkownikaLayoutRoute: PanelUzytkownikaLayoutRouteWithChildren,
}

const PanelUzytkownikaRouteWithChildren =
  PanelUzytkownikaRoute._addFileChildren(PanelUzytkownikaRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kategoria/$categoryId': typeof KategoriaCategoryIdRoute
  '/panel-uzytkownika': typeof PanelUzytkownikaLayoutRouteWithChildren
  '/produkt/$produktId': typeof ProduktProduktIdRoute
  '/uslugi/$categoryId': typeof UslugiCategoryIdRoute
  '/panel-uzytkownika/twoja-strona-sprzedawcy': typeof PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute
  '/panel-uzytkownika/twoja-umowa': typeof PanelUzytkownikaLayoutTwojaUmowaRoute
  '/panel-uzytkownika/twoje-dane': typeof PanelUzytkownikaLayoutTwojeDaneRoute
  '/panel-uzytkownika/twoje-produkty': typeof PanelUzytkownikaLayoutTwojeProduktyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kategoria/$categoryId': typeof KategoriaCategoryIdRoute
  '/panel-uzytkownika': typeof PanelUzytkownikaLayoutRouteWithChildren
  '/produkt/$produktId': typeof ProduktProduktIdRoute
  '/uslugi/$categoryId': typeof UslugiCategoryIdRoute
  '/panel-uzytkownika/twoja-strona-sprzedawcy': typeof PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute
  '/panel-uzytkownika/twoja-umowa': typeof PanelUzytkownikaLayoutTwojaUmowaRoute
  '/panel-uzytkownika/twoje-dane': typeof PanelUzytkownikaLayoutTwojeDaneRoute
  '/panel-uzytkownika/twoje-produkty': typeof PanelUzytkownikaLayoutTwojeProduktyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/kategoria/$categoryId': typeof KategoriaCategoryIdRoute
  '/panel-uzytkownika': typeof PanelUzytkownikaRouteWithChildren
  '/panel-uzytkownika/_layout': typeof PanelUzytkownikaLayoutRouteWithChildren
  '/produkt/$produktId': typeof ProduktProduktIdRoute
  '/uslugi/$categoryId': typeof UslugiCategoryIdRoute
  '/panel-uzytkownika/_layout/twoja-strona-sprzedawcy': typeof PanelUzytkownikaLayoutTwojaStronaSprzedawcyRoute
  '/panel-uzytkownika/_layout/twoja-umowa': typeof PanelUzytkownikaLayoutTwojaUmowaRoute
  '/panel-uzytkownika/_layout/twoje-dane': typeof PanelUzytkownikaLayoutTwojeDaneRoute
  '/panel-uzytkownika/_layout/twoje-produkty': typeof PanelUzytkownikaLayoutTwojeProduktyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kategoria/$categoryId'
    | '/panel-uzytkownika'
    | '/produkt/$produktId'
    | '/uslugi/$categoryId'
    | '/panel-uzytkownika/twoja-strona-sprzedawcy'
    | '/panel-uzytkownika/twoja-umowa'
    | '/panel-uzytkownika/twoje-dane'
    | '/panel-uzytkownika/twoje-produkty'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kategoria/$categoryId'
    | '/panel-uzytkownika'
    | '/produkt/$produktId'
    | '/uslugi/$categoryId'
    | '/panel-uzytkownika/twoja-strona-sprzedawcy'
    | '/panel-uzytkownika/twoja-umowa'
    | '/panel-uzytkownika/twoje-dane'
    | '/panel-uzytkownika/twoje-produkty'
  id:
    | '__root__'
    | '/'
    | '/kategoria/$categoryId'
    | '/panel-uzytkownika'
    | '/panel-uzytkownika/_layout'
    | '/produkt/$produktId'
    | '/uslugi/$categoryId'
    | '/panel-uzytkownika/_layout/twoja-strona-sprzedawcy'
    | '/panel-uzytkownika/_layout/twoja-umowa'
    | '/panel-uzytkownika/_layout/twoje-dane'
    | '/panel-uzytkownika/_layout/twoje-produkty'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KategoriaCategoryIdRoute: typeof KategoriaCategoryIdRoute
  PanelUzytkownikaRoute: typeof PanelUzytkownikaRouteWithChildren
  ProduktProduktIdRoute: typeof ProduktProduktIdRoute
  UslugiCategoryIdRoute: typeof UslugiCategoryIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KategoriaCategoryIdRoute: KategoriaCategoryIdRoute,
  PanelUzytkownikaRoute: PanelUzytkownikaRouteWithChildren,
  ProduktProduktIdRoute: ProduktProduktIdRoute,
  UslugiCategoryIdRoute: UslugiCategoryIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/kategoria/$categoryId",
        "/panel-uzytkownika",
        "/produkt/$produktId",
        "/uslugi/$categoryId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/kategoria/$categoryId": {
      "filePath": "kategoria/$categoryId.tsx"
    },
    "/panel-uzytkownika": {
      "filePath": "panel-uzytkownika",
      "children": [
        "/panel-uzytkownika/_layout"
      ]
    },
    "/panel-uzytkownika/_layout": {
      "filePath": "panel-uzytkownika/_layout.tsx",
      "parent": "/panel-uzytkownika",
      "children": [
        "/panel-uzytkownika/_layout/twoja-strona-sprzedawcy",
        "/panel-uzytkownika/_layout/twoja-umowa",
        "/panel-uzytkownika/_layout/twoje-dane",
        "/panel-uzytkownika/_layout/twoje-produkty"
      ]
    },
    "/produkt/$produktId": {
      "filePath": "produkt/$produktId.tsx"
    },
    "/uslugi/$categoryId": {
      "filePath": "uslugi/$categoryId.tsx"
    },
    "/panel-uzytkownika/_layout/twoja-strona-sprzedawcy": {
      "filePath": "panel-uzytkownika/_layout/twoja-strona-sprzedawcy.tsx",
      "parent": "/panel-uzytkownika/_layout"
    },
    "/panel-uzytkownika/_layout/twoja-umowa": {
      "filePath": "panel-uzytkownika/_layout/twoja-umowa.tsx",
      "parent": "/panel-uzytkownika/_layout"
    },
    "/panel-uzytkownika/_layout/twoje-dane": {
      "filePath": "panel-uzytkownika/_layout/twoje-dane.tsx",
      "parent": "/panel-uzytkownika/_layout"
    },
    "/panel-uzytkownika/_layout/twoje-produkty": {
      "filePath": "panel-uzytkownika/_layout/twoje-produkty.tsx",
      "parent": "/panel-uzytkownika/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
